version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hrm
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3031:3031"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=secret
      - DATABASE_PORT=5432
      - DATABASE_NAME=hrm
      - PORT=3031
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]
