# fly.toml app configuration file generated for hrm-golang on 2023-05-02T16:16:21+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hrm-golang"
primary_region = "nrt"

[http_service]
  internal_port = 3031
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
