# fly.toml app configuration file generated for hrm-golang on 2023-05-01T13:34:22+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hrm-golang"
primary_region = "nrt"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "3031"

[processes]
  migration = "make migrateup"

[http_service]
  processes = ["migration"]
  internal_port = 3031
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
