apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::721705570549:user/githubci
      username: github-ci
      groups:
        - system:masters
