name: Run unit test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

aws ecr get-login-password --region ap-southeast-1 | docker login --username kanatsanan --password-stdin 721705570549.dkr.ecr.ap-southeast-1.amazonaws.com/hrm-backend:d3eda8081e847e91624584daa7fa4deda98cc4a9
